### PR TITLE
perf: 优化跳转页

### PR DESCRIPTION
**Pull request by fit2bot**
perf: 优化跳转页

### CODE REVIEW

**Comment by Cainor** [comment]
Good luck guys. Nice work finding all code that has the same issue.

**Comment by ibuler** [comment]
@Cainor 
Thanks for your feedback

**Review by ibuler — APPROVED** [review]

**Review by LeeEirc — APPROVED** [review]

**Comment by Cainor** [comment]
@LeeEirc @ibuler 
Hi guys .. 
Following our previous discussion, I would like to request the registration of the identified security issue as a security advisory. Could you please initiate the process to obtain a CVE ID for this matter?

Additionally, I would appreciate it if my name, Mohammad Almazroa, could be acknowledged as the individual who reported the issue.

Thank you for your prompt attention to this matter, and I look forward to receiving updates on the CVE registration.

**Comment by ibuler** [comment]
@Cainor Ok, we request a security advisory，and add your as collaborator，you can check and update it，I'm sorry to forget that

**Comment by Cainor** [comment]
@ibuler  Thank you for your attention to this matter. I've reviewed it and just added the "credit" section.

**Pull request merged**
